name: kasir-grosir
environments:
  production:
    build:
      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader
      - name: Install NPM Dependencies
        run: npm ci
      - name: Build Assets
        run: npm run build
      - name: Optimize Laravel
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
    deploy:
      - name: Run Migrations
        run: php artisan migrate --force
      - name: Clear Caches
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan view:clear
    variables:
      APP_ENV: production
      APP_DEBUG: false
      LOG_LEVEL: error
      SESSION_DRIVER: database
      QUEUE_CONNECTION: database
      CACHE_STORE: database
      FILESYSTEM_DISK: s3
    services:
      - type: mysql
        plan: starter
      - type: redis
        plan: starter
